#ifndef _BLE_MESH_MODELS_H_
#define _BLE_MESH_MODELS_H_

#include "esp_ble_mesh_defs.h"
#include "esp_ble_mesh_config_model_api.h"

// Element 0x0002 – SIG Model IDs

// Configuration Server (built-in)
#define CONFIG_SRV_MODEL   ESP_BLE_MESH_MODEL_CFG_SRV

// Health Server & Client
#define HEALTH_SRV_MODEL   ESP_BLE_MESH_MODEL_HEALTH_SRV
#define HEALTH_CLI_MODEL   ESP_BLE_MESH_MODEL_HEALTH_CLI

// Generic Models
#define GEN_ONOFF_SRV_MODEL  ESP_BLE_MESH_MODEL_ID_GENERIC_ONOFF_SRV
#define GEN_ONOFF_CLI_MODEL  ESP_BLE_MESH_MODEL_ID_GENERIC_ONOFF_CLI
#define GEN_LEVEL_SRV_MODEL  ESP_BLE_MESH_MODEL_ID_GENERIC_LEVEL_SRV
#define GEN_LEVEL_CLI_MODEL  ESP_BLE_MESH_MODEL_ID_GENERIC_LEVEL_CLI
#define GEN_DEF_TRANS_SRV_MODEL  ESP_BLE_MESH_MODEL_ID_GENERIC_DEF_TRANS_TIME_SRV
#define GEN_DEF_TRANS_CLI_MODEL  ESP_BLE_MESH_MODEL_ID_GENERIC_DEF_TRANS_TIME_CLI
#define GEN_POWER_ONOFF_SRV_MODEL  ESP_BLE_MESH_MODEL_ID_GENERIC_POWER_ONOFF_SRV
#define GEN_POWER_ONOFF_CLI_MODEL  ESP_BLE_MESH_MODEL_ID_GENERIC_POWER_ONOFF_CLI
#define GEN_POWER_ONOFF_SETUP_SRV_MODEL ESP_BLE_MESH_MODEL_ID_GENERIC_POWER_ONOFF_SETUP_SRV
#define GEN_POWER_ONOFF_SETUP_CLI_MODEL ESP_BLE_MESH_MODEL_ID_GENERIC_POWER_ONOFF_SETUP_CLI

// Light Lightness Models
#define LIGHT_LIGHTNESS_SRV_MODEL      ESP_BLE_MESH_MODEL_ID_LIGHT_LIGHTNESS_SRV
#define LIGHT_LIGHTNESS_CLI_MODEL      ESP_BLE_MESH_MODEL_ID_LIGHT_LIGHTNESS_CLI
#define LIGHT_LIGHTNESS_SETUP_SRV_MODEL ESP_BLE_MESH_MODEL_ID_LIGHT_LIGHTNESS_SETUP_SRV

#endif /* _BLE_MESH_MODELS_H_ */
