#ifndef _BLE_MESH_OPCODES_H_
#define _BLE_MESH_OPCODES_H_

// Generic OnOff Model
#define OP_GENERIC_ONOFF_GET            0x8201
#define OP_GENERIC_ONOFF_SET            0x8202
#define OP_GENERIC_ONOFF_SET_UNACK      0x8203
#define OP_GENERIC_ONOFF_STATUS         0x8204

// Generic Level Model
#define OP_GENERIC_LEVEL_GET            0x8205
#define OP_GENERIC_LEVEL_SET            0x8206
#define OP_GENERIC_LEVEL_SET_UNACK      0x8207
#define OP_GENERIC_LEVEL_STATUS         0x8208

// Generic Default Transition Time Model
#define OP_GEN_DEF_TRANS_TIME_GET       0x820D
#define OP_GEN_DEF_TRANS_TIME_SET       0x820E
#define OP_GEN_DEF_TRANS_TIME_SET_UNACK 0x820F
#define OP_GEN_DEF_TRANS_TIME_STATUS    0x8210

// Generic Power OnOff Model
#define OP_GEN_POWER_ONOFF_GET          0x8211
#define OP_GEN_POWER_ONOFF_SET          0x8212
#define OP_GEN_POWER_ONOFF_SET_UNACK    0x8213
#define OP_GEN_POWER_ONOFF_STATUS       0x8214

// Generic Power OnOff Setup Model
#define OP_GEN_POWER_ONOFF_S_GET        0x8215
#define OP_GEN_POWER_ONOFF_S_SET        0x8216
#define OP_GEN_POWER_ONOFF_S_SET_UNACK  0x8217
#define OP_GEN_POWER_ONOFF_S_STATUS     0x8218

// Light Lightness Model
#define OP_LIGHT_LIGHTNESS_GET          0x824B
#define OP_LIGHT_LIGHTNESS_SET          0x824C
#define OP_LIGHT_LIGHTNESS_SET_UNACK    0x824D
#define OP_LIGHT_LIGHTNESS_STATUS       0x824E
#define OP_LIGHT_LIGHTNESS_LINEAR_GET   0x824F
#define OP_LIGHT_LIGHTNESS_LINEAR_SET   0x8250
#define OP_LIGHT_LIGHTNESS_LINEAR_UNACK 0x8251
#define OP_LIGHT_LIGHTNESS_LINEAR_STATUS 0x8252
#define OP_LIGHT_LIGHTNESS_LAST_GET     0x8253
#define OP_LIGHT_LIGHTNESS_LAST_STATUS  0x8254
#define OP_LIGHT_LIGHTNESS_DEFAULT_GET  0x8255
#define OP_LIGHT_LIGHTNESS_DEFAULT_STATUS 0x8256
#define OP_LIGHT_LIGHTNESS_RANGE_GET    0x8257
#define OP_LIGHT_LIGHTNESS_RANGE_STATUS 0x8258

// Light Lightness Setup Model
#define OP_LIGHT_LIGHTNESS_DEFAULT_SET      0x8259
#define OP_LIGHT_LIGHTNESS_RANGE_SET        0x825A
#define OP_LIGHT_LIGHTNESS_RANGE_SET_UNACK  0x825B

#endif /* _BLE_MESH_OPCODES_H_ */
